pluginManagement {
	repositories {
		maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
		maven { url "https://maven.aliyun.com/repository/public" }
		maven { url "https://maven.aliyun.com/repository/central" }
		gradlePluginPortal()
		mavenCentral()
		maven { url "https://maven.fabricmc.net/" }
		maven { url "https://maven.architectury.dev/" }
		maven { url "https://maven.minecraftforge.net/" }
	}
}

rootProject.name = mod_name

include("common")
include("fabric")
include("neoforge")
